# Generated by Django 3.2.16 on 2022-11-12 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=20)),
                ('identificacion', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=20)),
                ('ciudad', models.CharField(max_length=15)),
                ('codigoPostal', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=15)),
                ('pais', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30, null=True, unique=True)),
                ('telefono', models.CharField(max_length=15, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Factura_Envio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaFactura', models.DateTimeField()),
                ('precioTotal', models.IntegerField()),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factura_envio', to='Proceso.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen')),
                ('categoria', models.IntegerField(choices=[(1, 'LIGEROS'), (2, 'PESADOS'), (3, 'ESPECIALES'), (4, 'AGRICOLAS'), (5, 'OTROS')], verbose_name='Categoria')),
                ('subcategoria', models.IntegerField(choices=[(1, 'AUTOMOVIL'), (2, 'SUV/CAMIONETA'), (3, 'SERVICIO PUBLICO'), (4, 'CAMIONES GRANDES DIMENSIONES'), (5, 'FURGONETAS'), (6, 'VAN DE REPARTO'), (7, 'CAMIONES CARGA LIGERA'), (8, 'PICK-UPS'), (9, 'AMBULANCIAS'), (10, 'TRACTORES'), (11, 'TAXIS'), (12, 'GRUAS')], verbose_name='Subcategoria')),
                ('marca', models.IntegerField(choices=[(1, 'CHEVROLET'), (2, 'RENAULT'), (3, 'MAZDA'), (4, 'FORD'), (5, 'TOYOTA'), (6, 'SUZUKI'), (7, 'BMW'), (8, 'MERCEDEZ BENZ'), (9, 'VOLKSWAGEN'), (10, 'HYUNDAI'), (11, 'KIA'), (12, 'ATM'), (13, 'SONALIKA')], verbose_name='Marca')),
                ('color', models.IntegerField(choices=[(1, 'NEGRO'), (2, 'BLANCO'), (3, 'GRIS'), (4, 'AZUL'), (5, 'AZUL REY'), (6, 'ROJO'), (7, 'PLATA'), (8, 'BEIGE'), (9, 'AMARILLO'), (10, 'VERDE'), (11, 'BLANCO PERLA'), (12, 'NARANJA')], verbose_name='Color')),
                ('modelo', models.IntegerField(choices=[(1, 'LOGAN'), (2, 'SANDERO'), (3, 'STEPWAY'), (4, 'DUSTER'), (5, 'KANGOO'), (6, 'KWID'), (7, 'ONIX'), (8, 'JOY'), (9, 'AVEO'), (10, 'CAPTIVA'), (11, 'TRACKER'), (12, 'NHR'), (13, 'NPR'), (14, 'COROLLA'), (15, 'HILUX'), (16, 'FORTUNER'), (17, 'PRADO'), (18, 'VITARA'), (19, 'SWIFT'), (20, 'S CROSS'), (21, 'S PRESSO'), (22, 'JIMNY'), (23, 'RIO'), (24, 'PICANTO'), (25, 'CERATO'), (26, 'EKO TAXI'), (27, 'SONET'), (28, 'SELTOS'), (29, 'GOL'), (30, 'VOYAGE'), (31, 'AMAROK'), (32, 'TAOS'), (33, 'VIRTUS'), (34, 'VERSA'), (35, 'MARCH'), (36, 'KICKS'), (37, 'FRONTIER'), (38, 'V DRIVE'), (39, 'MAZDA 2'), (40, 'MAZDA 3'), (41, 'CX 5'), (42, 'CX 9'), (43, 'CX 30'), (44, 'ATOS'), (45, 'TUCSON'), (46, 'ACCENT'), (47, 'GRAVITI'), (48, 'GETZ'), (49, 'KONA'), (50, 'FHR'), (51, 'FRR'), (52, 'FRK'), (53, 'FQR'), (54, 'RANGER'), (55, 'OROCH'), (56, 'ALASKAN'), (57, 'YARIS CROSS'), (58, 'JMC CHR'), (59, 'QASHQAI'), (60, 'JAC JRR'), (61, 'RAV4'), (62, 'Q3'), (63, 'CACTUS'), (64, 'SPORTAGE'), (65, 'BUSETON OF917'), (66, 'SPRINTER 515'), (67, 'TRANSPORTER T5'), (68, 'MASTER'), (69, 'GRAND I10'), (70, 'T70'), (71, '90HP')], verbose_name='Modelo')),
                ('año', models.CharField(max_length=4, verbose_name='Año')),
                ('estado', models.IntegerField(choices=[(1, 'USADO'), (2, 'NUEVO')], verbose_name='Estado')),
                ('kilometrosRec', models.CharField(max_length=10, verbose_name='Kilometro')),
                ('numeroPasajeros', models.CharField(max_length=4, verbose_name='Numero de pasajeros')),
                ('numeroPuertas', models.IntegerField(choices=[(1, '2'), (2, '3'), (3, '4'), (4, '5'), (5, 'N/A')], verbose_name='Numero de puertas')),
                ('tipoMotor', models.IntegerField(choices=[(1, 'GASOLINA'), (2, 'DIESEL'), (3, 'GAS'), (4, 'NITRO'), (5, 'ELECTRICO'), (6, 'N/A')], verbose_name='Tipo de motor')),
                ('cilindraje', models.CharField(max_length=4, verbose_name='Cilindraje')),
                ('tipoTransmision', models.CharField(max_length=20, verbose_name='Tipo de transmision')),
                ('precio', models.IntegerField(null=True, verbose_name='Precio')),
                ('IVA', models.FloatField(null=True, verbose_name='IVA')),
                ('disponibilidad', models.IntegerField(verbose_name='Disponibilidad')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('idFacturaEnvio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venta', to='Proceso.factura_envio')),
                ('idVehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venta', to='Proceso.vehiculo')),
            ],
        ),
    ]
