# Generated by Django 3.2.16 on 2022-11-19 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Proceso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('decripcion', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='color',
            field=models.IntegerField(verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='estado',
            field=models.IntegerField(verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.IntegerField(verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.IntegerField(verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='numeroPuertas',
            field=models.IntegerField(verbose_name='Numero de puertas'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='subcategoria',
            field=models.IntegerField(verbose_name='Subcategoria'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipoMotor',
            field=models.IntegerField(verbose_name='Tipo de motor'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='idCategoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='Proceso.categoria'),
        ),
    ]
