# Generated by Django 3.2.16 on 2022-11-19 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proceso', '0002_auto_20221119_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='decripcion',
            new_name='descripcion',
        ),
    ]
