# Generated by Django 3.2.16 on 2022-11-19 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Proceso', '0003_rename_decripcion_categoria_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='NumeroPuertas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMotor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='color',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='numeroPuertas',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='subcategoria',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='tipoMotor',
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='idCategoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculo', to='Proceso.categoria'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='idColor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculo', to='Proceso.color'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='idEstado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculo', to='Proceso.estado'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='idMarca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculo', to='Proceso.marca'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='idModelo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculo', to='Proceso.modelo'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='idNumeroPuertas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculo', to='Proceso.numeropuertas'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='idSubcategoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculo', to='Proceso.subcategoria'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='idTipoMotor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculo', to='Proceso.tipomotor'),
        ),
    ]
